services:
  hmpps-adjustments-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-adjustments-api
    depends_on:
      - localstack
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,localstack

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps: