generic-service:
  nameOverride: hmpps-adjustments-api
  productId: "DPS014"
  serviceAccountName: hmpps-adjustments
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-adjustments-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-adjustments-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_ENABLED: "true"
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-adjustments-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-adjustments-prisoner-events-secret:
      HMPPS_SQS_QUEUES_PRISONERLISTENER_QUEUE_NAME: "sqs_queue_name"
    sqs-adjustments-prisoner-events-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONERLISTENER_DLQ_NAME: "sqs_queue_name"
    sqs-adjustments-unused-deductions-secret:
      HMPPS_SQS_QUEUES_UNUSEDDEDUCTIONS_QUEUE_NAME: "sqs_queue_name"
    sqs-adjustments-unused-deductions-dlq-secret:
      HMPPS_SQS_QUEUES_UNUSEDDEDUCTIONS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

  retryDlqCronjob:
    enabled: true

generic-prometheus-alerts:
  targetApplication: hmpps-adjustments-api
