---
# Per environment values which override defaults in hmpps-adjustments-api/values.yaml


generic-service:
  replicaCount: 2

  ingress:
    host: adjustments-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api-dev.hmpps.service.justice.gov.uk
    ADJUDICATIONS_API_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    REMANDANDSENTENCING_API_URL: https://remand-and-sentencing-api-dev.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search-dev.prison.service.justice.gov.uk

  # Switches off the allow list in the DEV env only.
  allowlist: null

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "farsight-devs-dev-hmpps_adjustments_prisoner_queue"
    - "farsight-devs-dev-hmpps_adjustments_prisoner_dlq"
    - "farsight-devs-dev-hmpps_unused_deductions_queue"
    - "farsight-devs-dev-hmpps_unused_deductions_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: legacy-replacement-alerts-non-prod

generic-data-analytics-extractor:
  serviceAccountName: hmpps-adjustments-dev-to-ap-s3
