---
# Per environment values which override defaults in hmpps-adjustments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: adjustments-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api-preprod.prison.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk
    ADJUDICATIONS_API_URL: https://manage-adjudications-api-preprod.hmpps.service.justice.gov.uk

  allowlist:
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    groups:
      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "farsight-devs-preprod-hmpps_adjustments_prisoner_queue"
    - "farsight-devs-preprod-hmpps_adjustments_prisoner_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: legacy-replacement-alerts-non-prod
