---
# Per environment values which override defaults in hmpps-adjustments-api/values.yaml

generic-service:
  ingress:
    host: adjustments-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api.hmpps.service.justice.gov.uk


  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  sqsAlertsQueueNames:
    - "farsight-devs-prod-hmpps_adjustments_prisoner_queue"
    - "farsight-devs-prod-hmpps_adjustments_prisoner_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: legacy-replacement-alerts
